audit: audit/**/*
auth: auth/**/*
config: config/**/*
exception: exception/**/*
globalutils: globalutils/**/*
member: member/**/*
pagingdto: pagingdto/**/*
study: study/**/*
studyaddons: studyaddons/**/*
flyway: /**/*.sql
yml: /**/*.yml
gradle: /**/*.gradle
